//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.01 at 10:09:55 AM EAT 
//


package org.moa.etlits.api.response;

import java.util.ArrayList;
import java.util.List;


public class EntryType {

    protected String description;

    protected List<ValueType> value;
    protected List<ParamType> parameter;

    protected String id;


    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }


    public List<ValueType> getValue() {
        if (value == null) {
            value = new ArrayList<ValueType>();
        }
        return this.value;
    }


    public List<ParamType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParamType>();
        }
        return this.parameter;
    }


    public String getId() {
        return id;
    }


    public void setId(String value) {
        this.id = value;
    }

}
